mutation UpdateTaskStatus($id: ID!, $status: String!) {
  update_maintenance_tasks(id: $id, data: { status: $status }) {
    id
    status
  }
}
mutation SubmitTaskUpdate(
  $id: ID!,
  $status: String!,
  $vibration: Float!,
  $imageUrl: String!,
  $lat: Float!,
  $long: Float!
) {
  update_maintenance_tasks(
    id: $id,
    data: {
      status: $status
      vibration: $vibration
      gps_lat: $lat
      gps_long: $long
      image_url: $imageUrl
      submitted_at: "NOW()"
    }
  ) {
    id
    status
    vibration
    image_url
  }
}
mutation AssignTask(
  $equipment_id: ID!,
  $technician_email: String!,
  $task_description: String!
) {
  insert_maintenance_tasks(
    data: {
      equipment_id: $equipment_id
      technician_email: $technician_email
      task_description: $task_description
      status: "ASSIGNED"
      submitted_at: "NOW()"
    }
  ) {
    id
    equipment_id
  }
}
